services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "3001:3001"
        environment:
            - MYSQL_PASSWORD=1234567
            - MYSQL_HOST=mysql
        volumes:
            - ./backend:/app # монтирование директории
            - /app/node_modules/ # исключение под-директории
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "3000:3000"
        environment:
            - BACKEND_URI=http://backend:3001
        depends_on:
            - backend
        networks:
            - app-network

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234567
            - MYSQL_DATABASE=goodwork
        ports: 
            - "33020:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 2s
            retries: 10
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
